name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Docker image
      run: docker build -t flask-app .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: mahedishato
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        docker tag flask-app ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Kubernetes
      run: |
        # Add your Kubernetes deployment commands here
        # For example:
        # kubectl apply -f kubernetes/deployment.yaml
        # kubectl apply -f kubernetes/service.yaml